/**
 * generate-settings.ts
 *
 * Reads the Keystatic `settings` singleton at BUILD TIME (Node context, where
 * node:fs is available and safe) and writes a plain, dependency-free module —
 * src/generated/settings.ts — that the Cloudflare Worker API routes
 * (src/pages/api/contact.ts, src/pages/api/adopt.ts) import instead of calling
 * the Keystatic filesystem reader at request time.
 *
 * Why: @keystatic/core/reader ultimately calls node:fs.readFile. Cloudflare
 * Workers' unenv-based node:fs shim is a throwing stub, so any API route that
 * reaches the reader at runtime crashes with:
 *   "Error: [unenv] fs.readFile is not implemented yet!"
 * Generating a plain object at build time keeps Keystatic as the single
 * source of truth while keeping node:fs out of the Worker bundle entirely.
 *
 * Wired in as the `prebuild` script in package.json, so it runs automatically
 * before every `pnpm build` (including Cloudflare Workers Builds in CI).
 *
 * Usage: npx tsx scripts/generate-settings.ts
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { createReader } from '@keystatic/core/reader';
import keystaticConfig from '../keystatic.config';
import { resolveContactEmail } from '../src/lib/settings-resolver';

async function main() {
  const reader = createReader(process.cwd(), keystaticConfig);
  const settings = await reader.singletons.settings.read();
  const contactEmail = resolveContactEmail(
    settings as { contactEmail?: string | null } | null
  );

  const outPath = join(process.cwd(), 'src', 'generated', 'settings.ts');
  const contents = `// AUTO-GENERATED by scripts/generate-settings.ts — do not edit by hand.
// Regenerated automatically via the \`prebuild\` script before every \`pnpm build\`.
// Source of truth: the Keystatic \`settings\` singleton (src/content/settings/global.yaml).
//
// This module intentionally has ZERO dependency on @keystatic/core or node:fs so it
// is safe to bundle into the Cloudflare Worker. See scripts/generate-settings.ts.

export interface GeneratedSiteSettings {
  contactEmail: string;
}

export const siteSettings: GeneratedSiteSettings = ${JSON.stringify(
    { contactEmail },
    null,
    2
  )};
`;

  writeFileSync(outPath, contents, 'utf-8');
  console.log(
    `[generate-settings] wrote ${outPath} (contactEmail=${contactEmail})`
  );
}

main().catch((error) => {
  console.error('[generate-settings] failed:', error);
  process.exit(1);
});
