const CAT_IMAGE_KEY_PATTERN = /^cats\/[^/]+\/[^/]+\.webp$/;

/**
 * True when `key` matches the R2 key shape used for cat images:
 * `cats/<catId>/<imageId>.webp` (see `imageKey` in `image-url.ts`).
 */
export function isCatImageKey(key: string): boolean {
  return CAT_IMAGE_KEY_PATTERN.test(key);
}

/**
 * Cat image keys that exist in R2 (`r2Keys`) but have no matching
 * `cat_images.r2_key` row in D1 (`dbKeys`). Pure diff, no I/O — the sweep
 * script (`scripts/sweep-orphan-images.ts`) supplies both lists.
 */
export function findOrphans(r2Keys: string[], dbKeys: string[]): string[] {
  const dbKeySet = new Set(dbKeys);
  return r2Keys.filter((key) => isCatImageKey(key) && !dbKeySet.has(key));
}

/**
 * Extracts every `<Key>...</Key>` value from an S3 ListObjectsV2 XML body.
 *
 * Lives here (not in the script) so it is importable and testable without
 * executing `sweep-orphan-images.ts`'s `main()`.
 *
 * Limitation: this is a plain regex scrape, not a real XML parser, so it
 * does NOT decode XML entities — a key containing a literal `&amp;` comes
 * back with the escape sequence intact rather than a decoded `&`. This is
 * safe in practice: cat image keys are generated by
 * `imageKey(catId, nanoid())` (see `image-url.ts`), and nanoid's default
 * alphabet (`A-Za-z0-9_-`) contains no character that XML or S3 would ever
 * escape, so a real cat image key can never contain an entity. If the key
 * scheme changes to allow arbitrary characters, this parser must be
 * revisited before it can be trusted with `--delete`.
 */
export function parseObjectKeys(xml: string): string[] {
  const keys: string[] = [];
  const pattern = /<Key>([^<]+)<\/Key>/g;
  let match: RegExpExecArray | null = pattern.exec(xml);
  while (match !== null) {
    keys.push(match[1]);
    match = pattern.exec(xml);
  }
  return keys;
}
