import { describe, expect, it } from 'vitest';
import { findOrphans, isCatImageKey, parseObjectKeys } from '../src/orphans';

describe('isCatImageKey', () => {
  it('accepts a well-formed cat image key', () => {
    expect(isCatImageKey('cats/abc123/img456.webp')).toBe(true);
  });

  it('rejects keys outside the cats/ prefix', () => {
    expect(isCatImageKey('settings/logo.webp')).toBe(false);
  });

  it('rejects non-webp extensions', () => {
    expect(isCatImageKey('cats/abc123/img456.png')).toBe(false);
  });

  it('rejects keys with too few path segments', () => {
    expect(isCatImageKey('cats/img456.webp')).toBe(false);
  });

  it('rejects keys with too many path segments', () => {
    expect(isCatImageKey('cats/abc123/nested/img456.webp')).toBe(false);
  });
});

describe('findOrphans', () => {
  it('returns cat image keys present in R2 but absent from the DB', () => {
    const r2Keys = [
      'cats/abc123/img1.webp',
      'cats/abc123/img2.webp',
      'cats/def456/img3.webp',
    ];
    const dbKeys = ['cats/abc123/img1.webp'];

    expect(findOrphans(r2Keys, dbKeys)).toEqual([
      'cats/abc123/img2.webp',
      'cats/def456/img3.webp',
    ]);
  });

  it('returns an empty array when every R2 key has a DB row', () => {
    const r2Keys = ['cats/abc123/img1.webp'];
    const dbKeys = ['cats/abc123/img1.webp'];

    expect(findOrphans(r2Keys, dbKeys)).toEqual([]);
  });

  it('ignores non-cat-image keys even if absent from the DB', () => {
    const r2Keys = ['settings/logo.webp', 'cats/abc123/img1.webp'];
    const dbKeys: string[] = [];

    expect(findOrphans(r2Keys, dbKeys)).toEqual(['cats/abc123/img1.webp']);
  });

  it('returns an empty array for empty input', () => {
    expect(findOrphans([], [])).toEqual([]);
  });
});

describe('parseObjectKeys', () => {
  it('extracts every key from a realistic multi-object ListObjectsV2 body', () => {
    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Name>animals-vida-digna-images</Name>
  <Prefix>cats/</Prefix>
  <KeyCount>2</KeyCount>
  <MaxKeys>1000</MaxKeys>
  <IsTruncated>false</IsTruncated>
  <Contents>
    <Key>cats/abc123/img1.webp</Key>
    <LastModified>2026-01-01T00:00:00.000Z</LastModified>
    <ETag>"d41d8cd98f00b204e9800998ecf8427e"</ETag>
    <Size>12345</Size>
    <StorageClass>STANDARD</StorageClass>
  </Contents>
  <Contents>
    <Key>cats/def456/img2.webp</Key>
    <LastModified>2026-01-02T00:00:00.000Z</LastModified>
    <ETag>"e2fc714c4727ee9395f324cd2e7f331f"</ETag>
    <Size>54321</Size>
    <StorageClass>STANDARD</StorageClass>
  </Contents>
</ListBucketResult>`;

    expect(parseObjectKeys(xml)).toEqual([
      'cats/abc123/img1.webp',
      'cats/def456/img2.webp',
    ]);
  });

  it('returns an empty array for an empty result', () => {
    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Name>animals-vida-digna-images</Name>
  <Prefix>cats/</Prefix>
  <KeyCount>0</KeyCount>
  <MaxKeys>1000</MaxKeys>
  <IsTruncated>false</IsTruncated>
</ListBucketResult>`;

    expect(parseObjectKeys(xml)).toEqual([]);
  });

  it('does not decode XML entities in a key (documented limitation)', () => {
    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Name>animals-vida-digna-images</Name>
  <KeyCount>1</KeyCount>
  <IsTruncated>false</IsTruncated>
  <Contents>
    <Key>cats/abc123/AT&amp;T.webp</Key>
    <LastModified>2026-01-01T00:00:00.000Z</LastModified>
    <ETag>"d41d8cd98f00b204e9800998ecf8427e"</ETag>
    <Size>12345</Size>
    <StorageClass>STANDARD</StorageClass>
  </Contents>
</ListBucketResult>`;

    // The regex-based parser does NOT unescape XML entities, so the raw
    // `&amp;` survives verbatim instead of becoming `&`. This is safe in
    // practice because cat image keys are generated by
    // `imageKey(catId, nanoid())` (see `src/image-url.ts`), and nanoid's
    // default alphabet contains no characters that XML/S3 would escape —
    // so a real cat image key can never contain an entity. Documented as
    // a limitation rather than silently relied upon.
    expect(parseObjectKeys(xml)).toEqual(['cats/abc123/AT&amp;T.webp']);
  });

  it('extracts keys from a truncated/paginated response', () => {
    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Name>animals-vida-digna-images</Name>
  <Prefix>cats/</Prefix>
  <KeyCount>1</KeyCount>
  <MaxKeys>1</MaxKeys>
  <IsTruncated>true</IsTruncated>
  <NextContinuationToken>token-abc123</NextContinuationToken>
  <Contents>
    <Key>cats/abc123/img1.webp</Key>
    <LastModified>2026-01-01T00:00:00.000Z</LastModified>
    <ETag>"d41d8cd98f00b204e9800998ecf8427e"</ETag>
    <Size>12345</Size>
    <StorageClass>STANDARD</StorageClass>
  </Contents>
</ListBucketResult>`;

    expect(parseObjectKeys(xml)).toEqual(['cats/abc123/img1.webp']);
  });
});

describe('findOrphans composed with parseObjectKeys', () => {
  it('goes from a realistic XML fixture to an orphan-key list end to end', () => {
    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Name>animals-vida-digna-images</Name>
  <Prefix>cats/</Prefix>
  <KeyCount>3</KeyCount>
  <MaxKeys>1000</MaxKeys>
  <IsTruncated>false</IsTruncated>
  <Contents>
    <Key>cats/abc123/img1.webp</Key>
    <LastModified>2026-01-01T00:00:00.000Z</LastModified>
    <ETag>"d41d8cd98f00b204e9800998ecf8427e"</ETag>
    <Size>12345</Size>
    <StorageClass>STANDARD</StorageClass>
  </Contents>
  <Contents>
    <Key>cats/abc123/img2.webp</Key>
    <LastModified>2026-01-02T00:00:00.000Z</LastModified>
    <ETag>"e2fc714c4727ee9395f324cd2e7f331f"</ETag>
    <Size>54321</Size>
    <StorageClass>STANDARD</StorageClass>
  </Contents>
  <Contents>
    <Key>cats/def456/img3.webp</Key>
    <LastModified>2026-01-03T00:00:00.000Z</LastModified>
    <ETag>"5d41402abc4b2a76b9719d911017c592"</ETag>
    <Size>98765</Size>
    <StorageClass>STANDARD</StorageClass>
  </Contents>
</ListBucketResult>`;

    const r2Keys = parseObjectKeys(xml);
    const dbKeys = ['cats/abc123/img1.webp'];

    expect(findOrphans(r2Keys, dbKeys)).toEqual([
      'cats/abc123/img2.webp',
      'cats/def456/img3.webp',
    ]);
  });
});
